version: "3.9"

services:
  listener:
    extends:
      file: docker-compose.yml
      service: listener
    build:
      context: listener
      dockerfile: Dockerfile.dev
    volumes:
      - ./listener/cmd:/app/cmd
      - ./listener/internal:/app/internal

  mongo:
    extends:
      file: docker-compose.yml
      service: mongo

  ui:
    extends:
      file: docker-compose.yml
      service: ui

  # Below services simulates web3signer setup
  
  web3signer:
    build:
      context: web3signer/signer
      dockerfile: Dockerfile
    networks:
      monitoring_dev_network:
        aliases:
          - web3signer.web3signer.dappnode

  flyway:
    build:
      context: web3signer/flyway
      dockerfile: Dockerfile
    networks:
      monitoring_dev_network:
        aliases:
          - flyway.web3signer.dappnode
    depends_on:
      postgres:
        condition: service_started

  postgres:
    build:
      context: web3signer/postgres
      dockerfile: Dockerfile
    networks:
      monitoring_dev_network:
        aliases:
          - postgres.web3signer.dappnode
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5

  brain:
    build:
      context: web3signer/brain
      dockerfile: Dockerfile
    networks:
      monitoring_dev_network:
        aliases:
          - brain.web3signer.dappnode

networks:
  monitoring_dev_network:
    name: monitoring_dev_network
  

volumes:
  mongo-data:
