version: "3.9"

services:
  listener:
    build:
      context: listener
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MONGO_DB_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_DB_API_PORT}"
      MONGO_DB_NAME: "${MONGO_DB_NAME}"
      API_PORT: "${API_PORT}"
      LOG_LEVEL: "${LOG_LEVEL}"
      BYPASS_VALIDATORS_FILTERING: "${BYPASS_VALIDATORS_FILTERING}"
    depends_on:
      - mongo
    container_name: listener

  ui:
    build:
      context: ui
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_DB_API_PORT}"
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      ME_CONFIG_BASICAUTH_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      PORT: 8081
    depends_on:
      - mongo
    container_name: ui
    ports:
      - "8081:8081" # required for mac os access UI

  mongo:
    build:
      context: mongo
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: "${MONGO_DB_NAME}"
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    container_name: mongo

volumes:
  mongo-data:
