FROM ghcr.io/dappnode/staking-brain:0.1.17
# Mandatory envs for brain
ENV NETWORK=mainnet
ENV _DAPPNODE_GLOBAL_EXECUTION_CLIENT_MAINNET="erigon.dnp.dappnode.eth"
ENV _DAPPNODE_GLOBAL_CONSENSUS_CLIENT_MAINNET="prysm.dnp.dappnode.eth"
ENV SHARE_DATA_WITH_DAPPNODE="true"
ENV VALIDATORS_MONITOR_URL="http://listener.dappnode:8080"
ENV SHARE_CRON_INTERVAL="3600"