FROM staking-brain:0.1.18
# Mandatory envs for brain
ENV NETWORK=holesky
ENV _DAPPNODE_GLOBAL_EXECUTION_CLIENT_HOLESKY="holesky-geth.dnp.dappnode.eth"
ENV _DAPPNODE_GLOBAL_CONSENSUS_CLIENT_HOLESKY="prysm-holesky.dnp.dappnode.eth"
ENV SHARE_DATA_WITH_DAPPNODE="true"
ENV VALIDATORS_MONITOR_URL="http://listener.dappnode:8080"
ENV SHARE_CRON_INTERVAL="3600"